Friends 27
TietoDigitalization/friends-tap pull request #45
Opened 2023-11-17 10:00 UTC by EliasHolmerTietoevry

2023-11-17 15:55 UTC, liviu-florin-ilie requested changes
Grattis för 1a uppgift på backend.
Jag läggade några kommentarer och gjörde ett litet refactorisering.
Ta gärna en titt på mina kommentarer och säga till om det är inte någonting som inte stämmer.

2023-11-17 15:55 UTC, liviu-florin-ilie commented on friends-survey-api/src/main/kotlin/com/tietoevry/survey/service/SurveyResponseService.kt
> +                    println(jsonResponse)
den måste bort.

2023-11-17 15:55 UTC, liviu-florin-ilie commented on friends-survey-api/src/main/kotlin/com/tietoevry/survey/service/SurveyResponseService.kt
> +
https://stackoverflow.com/questions/16638637/whats-faster-regex-or-string-operations

2023-11-17 15:55 UTC, liviu-florin-ilie commented on friends-survey-api/src/main/kotlin/com/tietoevry/survey/service/SurveyResponseService.kt
> +        private val logger = LoggerFactory.getLogger(SurveyResponseService::class.java)
Den används inte.

2023-11-20 07:08 UTC, EliasHolmerTietoevry commented on friends-survey-api/pom.xml
> +
Jag kan inte skillnaden på dem och har ingen preferens så du får gärna ta ett beslut där och informera om för/nackdel.

2023-11-20 07:10 UTC, EliasHolmerTietoevry commented on friends-survey-api/src/main/kotlin/com/tietoevry/survey/service/SurveyResponseService.kt
> +
Inte riktigt med på vad du menar? Enligt länken är string-operations snabbare vilket är det som är implementerat i koden.

2023-11-24 12:16 UTC, merged